# Generated by Django 5.1.1 on 2024-10-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.IntegerField()),
                ("contact", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.IntegerField()),
                ("contact", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("identity", models.IntegerField()),
                ("registration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentPost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("creation_date", models.DateField()),
                ("salary", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("upload_date", models.DateField()),
                ("content", models.TextField()),
                (
                    "receiver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_materials",
                        to="myapp.student",
                    ),
                ),
                (
                    "uploader_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_materials",
                        to="myapp.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("creation_date", models.DateField()),
                ("salary", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.tutor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "reviewed_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to="myapp.user",
                    ),
                ),
                (
                    "reviewer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to="myapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "related_post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.jobpost"
                    ),
                ),
                (
                    "recipient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
