# Generated by Django 5.1.1 on 2024-11-04 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id_post",
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="postsubject",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_id_subject",
                to="myapp.post",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id_student",
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id_tutor",
                to="myapp.user",
            ),
        ),
    ]
