# Generated by Django 5.1.1 on 2024-10-16 07:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitmentpost",
            old_name="id",
            new_name="post_id",
        ),
        migrations.RemoveField(
            model_name="recruitmentpost",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="recruitmentpost",
            name="creator_id",
        ),
        migrations.RemoveField(
            model_name="recruitmentpost",
            name="salary",
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="emailAddress",
            field=models.EmailField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="endDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="fullLocation",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="location",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="startDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="subjects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="telephoneNumber",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recruitmentpost",
            name="user_id",
            field=models.ForeignKey(
                default="-1",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
            preserve_default=False,
        ),
    ]
