# Generated by Django 5.1.1 on 2024-10-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_id_recruitmentpost_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentpost",
            name="content",
            field=models.TextField(default="content"),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="emailAddress",
            field=models.EmailField(default="emailAddress", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="endDate",
            field=models.DateField(default="2021-01-01"),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="fullLocation",
            field=models.CharField(default="fullLocation", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="location",
            field=models.CharField(default="location", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="startDate",
            field=models.DateField(default="2021-01-01"),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="telephoneNumber",
            field=models.CharField(default="telephoneNumber", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="title",
            field=models.CharField(default="title", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="user_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
    ]
