# Generated by Django 5.1.1 on 2024-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_post_user_id_alter_postsubject_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="rateNum",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
