# Generated by Django 5.1.1 on 2024-10-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_recruitmentpost_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentpost",
            name="post_id",
            field=models.BigAutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="user_id",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
    ]
