# Generated by Django 5.1.1 on 2024-11-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_tutor_rate_alter_tutor_ratenum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-notificationDate"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-postDate"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="studymaterial",
            options={"ordering": ["-upload_date"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-registration_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
