# Generated by Django 5.1.1 on 2024-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_recruitmentpost_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentpost",
            name="post_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
