# Generated by Django 5.1.1 on 2024-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_notification_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_announcement",
            field=models.BooleanField(default=False),
        ),
    ]
