# Generated by Django 5.1.1 on 2024-10-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_recruitmentpost_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentpost",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
