# Generated by Django 5.1.1 on 2024-11-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_notification_is_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "announcement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("announcementDate", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-announcementDate"],
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_announcement",
        ),
    ]
