# Generated by Django 5.1.1 on 2024-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_post_options_post_myapp_post_title_c151dc_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_id"], name="myapp_post_post_id_5768e7_idx"
            ),
        ),
    ]
