# Generated by Django 5.1.1 on 2024-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_post_myapp_post_post_id_5768e7_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notificationDate"], name="myapp_notif_notific_08cde0_idx"
            ),
        ),
    ]
