# Generated by Django 5.1.1 on 2024-10-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_recruitmentpost_is_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="id",
            new_name="post_id",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="creator_id",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_post_id",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="emailAddress",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="fullLocation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_completed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="subjects",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="telephoneNumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
