# Generated by Django 5.1.1 on 2024-10-21 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_rename_id_jobpost_post_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="recruitmentpost",
            old_name="user_id",
            new_name="user",
        ),
    ]
