# Generated by Django 5.1.1 on 2024-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="file",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="materials/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
