# Generated by Django 5.1.1 on 2024-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(),
        ),
    ]
