# Generated by Django 5.1.1 on 2024-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
