# Generated by Django 5.1.1 on 2024-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_review_date_alter_studymaterial_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
